### PR TITLE
Initial Draft of Objectives and Key Results for Q1 of 2018

### PR DESCRIPTION
**Pull request by lidel**
This PR adds `objectives-and-key-results/` directory along with the first document for Q1.
I tried to keep them straight to the point and realistic – let me know how I can improve it. 

(@diasdavid,  is this what you had in mind?)

### CODE REVIEW

**Comment by lidel** [comment]
cc @alanshaw @olizilla for sanity-check of Brave OKR :)

**Comment by lidel** [comment]
Ok, I moved my draft to 'OKR Proposals' section. 
This enables us to merge this and let others to PR against it, as suggested in #65

@diasdavid Y/n ?

**Comment by VictorBjelkholm** [comment]
No mention of exposing `window.ipfs`? :(

**Comment by olizilla** [comment]
doc is a WIP, we'll be adding more to it!

**Comment by lidel** [comment]
@VictorBjelkholm  feel free to add it in a new PR :) 
We are already tracking this effort in https://github.com/ipfs-shipyard/ipfs-companion/issues/330, I feel it could be shipped as an experiment in Q1 (worse case scenario Q2 if there are big roadblocks). But we definitely started working on it (eg. @alanshaw's  https://github.com/tableflip/ipfs-postmsg-proxy)

**Comment by VictorBjelkholm** [comment]
Thanks @olizilla and @lidel :) Seen all the awesome work, especially ipfs-postmsg-proxy which seems great so far. Was just wary that it was not mentioned in the document.

**Comment by alanshaw** [comment]
Some news today:
screen shot 2018-01-04 at 15 32 25

**Pull request merged**
